"
## For the Class part:
Represent an announcement called when a a line of codes has 2 rhythms ( sequencers)

## For the Responsibility part: 
- I am used when two sequencers are added to announce it to the PerformanceRecorder.

## For the Collaborators Part:
 PerformanceRecorder announcer.

## how to create instances :
```
DoubleRhythmAnnouncement new.
```

"
Class {
	#name : 'DoubleRhythmAnnouncement',
	#superclass : 'Announcement',
	#category : 'CoypuRecorder-Announcements',
	#package : 'CoypuRecorder',
	#tag : 'Announcements'
}
